name: Staging CI

on:
  pull_request:
    branches: ["staging/feature"]
    types: ["closed"]

jobs:
  staging_build:
    runs-on: ["self-hosted", testrunner]
    steps:
      - uses: actions/checkout@v3

      - name: docker build node johnreactrepo
        run: docker build -t appxtract/johnreactrepo:staging client/

      - name: login to docker
        run: docker login -u appxtract -p ${{secrets.DOCKER_PASSWORD}}

      - run: docker push appxtract/johnreactrepo:staging

  deploy_staging:
    runs-on: ["self-hosted", testrunner]
    needs: staging_build
    steps:
      - name: pull docker image
        run: docker pull appxtract/johnreactrepo:staging

      - name: run staging image
        run: docker run -d -p 5173:5173 appxtract/johnreactrepo:staging
